title: "fthnmr"
description: "Modern Mycology, Cultivation & Experiments"
baseurl: ""
url: "https://fthnmr.com"

remote_theme: mrzool/jekyll-theme-contei
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
include:
  - _pages
  - assets
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
