# Site settings
title: "fthnmr"
description: "Modern Mycology, Cultivation & Experiments"
url: "https://fthnmr.com"
baseurl: "" # leave empty for root deployment

# Build settings
theme: jekyll-theme-hacker
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Include / exclude files
include:
  - _pages
  - assets
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock

# Permalinks
permalink: pretty # removes .html from URLs

# Defaults for pages and posts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author: Yusha
  - scope:
      path: ""
      type: posts
    values:
      layout: default
      author: Yusha